name       : sddm
version    : 0.17.0
release    : 7
source     :
    - https://github.com/sddm/sddm/releases/download/v0.17.0/sddm-0.17.0.tar.gz : 0743895b082becb24318564da0de3c2d4d93d567cee78174343716806a6c5704
license    :
    - CC-BY-3.0
    - GPL-2.0-or-later
component  : desktop
summary    : Modern display manager for X11 and Wayland
description: |
    SDDM is a modern display manager for X11 and Wayland aiming to be fast, simple and beautiful. It uses modern technologies like QtQuick, which in turn gives the designer the ability to create smooth, animated user interfaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(xcb)
    - extra-cmake-modules
rundeps    :
    - linux-driver-management-sddm-integration
    - qt5-virtualkeyboard
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-Solus-defaults.patch
    %patch -p1 < $pkgfiles/Dont-quit-on-SIGHUP.patch
    %cmake_ninja -DCMAKE_INSTALL_LIBEXECDIR=%libdir%/%PKGNAME% \
           -DSYSTEMD_SYSTEM_UNIT_DIR=%libdir%/systemd/system
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Start by default
    install -d -m 00755 $installdir/%libdir%/systemd/system/graphical.target.wants
    ln -s %libdir%/systemd/system/sddm.service $installdir/%libdir%/systemd/system/displaymanager.service
    ln -s %libdir%/systemd/system/sddm.service $installdir/%libdir%/systemd/system/graphical.target.wants/sddm.service

    install -D -m 00644 $pkgfiles/sddm.sysusers $installdir/%libdir%/sysusers.d/sddm.conf
    install -D -m 00644 $pkgfiles/sddm.tmpfiles $installdir/%libdir%/tmpfiles.d/sddm.conf
    install -D -m 00644 $pkgfiles/sddm.pam $installdir/etc/pam.d/sddm
    install -D -m 00644 $pkgfiles/sddm-autologin.pam $installdir/etc/pam.d/sddm-autologin
    install -D -m 00644 $pkgfiles/sddm.conf $installdir/usr/share/sddm/sddm.conf.d/10_solus_default.conf

    # File provided by linux-driver-management-sddm-integration
    rm $installdir/usr/share/sddm/scripts/Xsetup

    # Already ships our default config
    rm $installdir/etc/sddm.conf
    %qml_cache
