name       : sddm
version    : 0.19.0
release    : 31
source     :
    - https://github.com/sddm/sddm/archive/refs/tags/v0.19.0.tar.gz : e76da1f13d5ad5e0179e3fec57543126044339405ef19c397e105e0807bd4e41
license    :
    - CC-BY-3.0
    - GPL-2.0-or-later
component  : desktop
summary    : Modern display manager for X11 and Wayland
description: |
    SDDM is a modern display manager for X11 and Wayland aiming to be fast, simple and beautiful. It uses modern technologies like QtQuick, which in turn gives the designer the ability to create smooth, animated user interfaces.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - pkgconfig(xcb)
    - extra-cmake-modules
rundeps    :
    - linux-driver-management-sddm-integration
    - qt5-virtualkeyboard
    - setxkbmap
    - xauth
    - xhost
    - xkbcomp
    - xkeyboard-config
setup      : |
    %apply_patches
    %cmake_ninja -DCMAKE_INSTALL_LIBEXECDIR=%libdir%/%PKGNAME% \
           -DSYSTEMD_SYSTEM_UNIT_DIR=%libdir%/systemd/system
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Start by default
    install -dm00755 $installdir/%libdir%/systemd/system/graphical.target.wants
    ln -s %libdir%/systemd/system/sddm.service $installdir/%libdir%/systemd/system/displaymanager.service
    ln -s %libdir%/systemd/system/sddm.service $installdir/%libdir%/systemd/system/graphical.target.wants/sddm.service

    install -Dm00644 $pkgfiles/sddm.sysusers $installdir/%libdir%/sysusers.d/sddm.conf
    install -Dm00644 $pkgfiles/sddm.tmpfiles $installdir/%libdir%/tmpfiles.d/sddm.conf
    install -Dm00644 $installdir/etc/pam.d/sddm-greeter $installdir/usr/share/defaults/etc/pam.d/sddm-greeter
    rm -rf $installdir/etc/pam.d
    install -Dm00644 $pkgfiles/sddm.pam $installdir/usr/share/defaults/etc/pam.d/sddm
    install -Dm00644 $pkgfiles/sddm-autologin.pam $installdir/usr/share/defaults/etc/pam.d/sddm-autologin
    install -Dm00644 $pkgfiles/sddm.conf $installdir/usr/share/sddm/sddm.conf.d/10_solus_default.conf
    rm -rf $installdir/etc
    # File provided by linux-driver-management-sddm-integration
    rm $installdir/usr/share/sddm/scripts/Xsetup

    %qml_cache
